name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./src/app"
      - name: Set up Python 3.13
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest_asyncio
        if [ -f src/requirements.txt ]; then pip install -r src/requirements.txt; fi
    - name: Add butane
      run: |
        mkdir -p $HOME/.local/bin
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        wget https://github.com/coreos/butane/releases/download/v0.25.0/butane-x86_64-unknown-linux-gnu
        mv butane-x86_64-unknown-linux-gnu $HOME/.local/bin/butane
    - name: Test with pytest
      run: |
        pytest
