name: semantic-pr-title

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]

permissions:
  pull-requests: read
  statuses: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            feat
            fix
            chore
            docs
            style
            refactor
            perf
            test
            ci
            build
            revert
          requireScope: false
          allowBreakingChanges: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
